apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-entertainment-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hub-entertainment
  template:
    metadata:
      labels:
        app: hub-entertainment
    spec:
      containers:
        - name: hub-entertainment-container
          image: hub-entertainment-mega:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80