apiVersion: v1
kind: Service
metadata: 
  name: hub-entertainment-mega
spec:
  type: NodePort
  selector:
    app: hub-entertainment-mega
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000